### ISSUE TITLE
error cannot start

### ISSUE THREAD

**Issue by x0rzkov** [iterativo-git/dockerdoo#46]
Hi guys,

Hope you are all well !

While starting the following command:
```shell
docker-compose -f docker-compose.yml -f dev-hosted.yml up
```

I have the following error message from docker-compose:

```bash
dockerdoo % docker-compose -f docker-compose.yml -f dev-hosted.yml up
Pulling wdb (kozea/wdb:3.3.0)...
3.3.0: Pulling from kozea/wdb
4a56a430b2ba: Pull complete
4b5cacb629f5: Pull complete
14408c8d4f9a: Pull complete
ea67eaa7dd42: Pull complete
4d134ac3fe4b: Pull complete
4c55f6f5d7f0: Pull complete
6ae475e50652: Pull complete
6f4152644229: Pull complete
6933d3d46042: Pull complete
dc4548de44c0: Pull complete
Digest: sha256:f659d7fbf24c70b908fab02fd05d8f31d128df7b75934678b4e5865dd2836b69
Status: Downloaded newer image for kozea/wdb:3.3.0
Starting dockerdoo_db_1 ... done
Creating dockerdoo_wdb_1 ... done
Recreating dockerdoo_odoo_1 ... done
Attaching to dockerdoo_db_1, dockerdoo_wdb_1, dockerdoo_odoo_1
db_1    | 
db_1    | PostgreSQL Database directory appears to contain a database; Skipping initialization
db_1    | 
db_1    | 2019-12-12 14:49:01.411 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db_1    | 2019-12-12 14:49:01.411 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db_1    | 2019-12-12 14:49:01.504 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db_1    | 2019-12-12 14:49:03.629 UTC [25] LOG:  database system was interrupted; last known up at 2019-12-11 20:10:24 UTC
db_1    | 2019-12-12 14:49:05.429 UTC [25] LOG:  database system was not properly shut down; automatic recovery in progress
db_1    | 2019-12-12 14:49:05.509 UTC [25] LOG:  redo starts at 0/1652F00
db_1    | 2019-12-12 14:49:05.509 UTC [25] LOG:  invalid record length at 0/1652F38: wanted 24, got 0
db_1    | 2019-12-12 14:49:05.509 UTC [25] LOG:  redo done at 0/1652F00
db_1    | 2019-12-12 14:49:06.390 UTC [1] LOG:  database system is ready to accept connections
odoo_1  | The variable $ODOO_EXTRA_ADDONS is empty, using default addons_path
odoo_1  | /entrypoint.sh: line 86: /opt/odoo/odoo-bin: No such file or directory
odoo_1  | The variable $ODOO_EXTRA_ADDONS is empty, using default addons_path
odoo_1  | /entrypoint.sh: line 86: /opt/odoo/odoo-bin: No such file or directory
dockerdoo_odoo_1 exited with code 127
odoo_1  | /entrypoint.sh: line 86: /opt/odoo/odoo-bin: No such file or directory
dockerdoo_odoo_1 exited with code 0
odoo_1  | The variable $ODOO_EXTRA_ADDONS is empty, using default addons_path
odoo_1  | /entrypoint.sh: line 86: /opt/odoo/odoo-bin: No such file or directory
dockerdoo_odoo_1 exited with code 127
odoo_1  | The variable $ODOO_EXTRA_ADDONS is empty, using default addons_path
odoo_1  | /entrypoint.sh: line 86: /opt/odoo/odoo-bin: No such file or directory
dockerdoo_odoo_1 exited with code 127
odoo_1  | The variable $ODOO_EXTRA_ADDONS is empty, using default addons_path
odoo_1  | /entrypoint.sh: line 86: /opt/odoo/odoo-bin: No such file or directory
dockerdoo_odoo_1 exited with code 127
odoo_1  | /entrypoint.sh: line 86: /opt/odoo/odoo-bin: No such file or directory
dockerdoo_odoo_1 exited with code 127
odoo_1  | The variable $ODOO_EXTRA_ADDONS is empty, using default addons_path
odoo_1  | /entrypoint.sh: line 86: /opt/odoo/odoo-bin: No such file or directory
dockerdoo_odoo_1 exited with code 127
odoo_1  | The variable $ODOO_EXTRA_ADDONS is empty, using default addons_path
odoo_1  | /entrypoint.sh: line 86: /op
```

My host machine is Macbook Air.

2 questions
- Can you help me to solve the problem ?
- Have you considered to use docker-sync to sync source code more fastly with the **odoo** named container ?

References:
- official repo for docker-sync: https://github.com/EugenMayer/docker-sync
- config example: https://github.com/aliuosio/mage2.docker/blob/master/docker-sync.yml

Cheers,
X

**Comment by x0rzkov** [comment]
weird as 
```bash
docker-compose -f docker-compose.yml -f dev-hosted.yml config
```
gives
```bash
dockerdoo % docker-compose -f docker-compose.yml -f dev-hosted.yml config
networks:
  default:
    external: true
    name: cloudbuild
  odoonet: {}
services:
  db:
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: odoo
      POSTGRES_USER: odoo
    image: postgres:11
    networks:
      odoonet: {}
    restart: unless-stopped
    volumes:
    - psql:/var/lib/postgresql/data/pgdata:rw
  odoo:
    command:
    - odoo
    - --dev
    - wdb,reload,qweb,werkzeug,xml
    depends_on:
    - db
    - wdb
    environment:
      ADMIN_PASSWORD: my-weak-password
      BOOTSTRAP_VERSION: ''
      DBFILTER: .*
      DB_ENV_POSTGRES_PASSWORD: odoo
      DB_ENV_POSTGRES_USER: odoo
      DB_MAXCONN: '64'
      DB_PORT_5432_TCP_ADDR: db
      DB_PORT_5432_TCP_PORT: '5432'
      DB_SSLMODE: prefer
      DB_TEMPLATE: template1
      HTTP_INTERFACE: 0.0.0.0
      HTTP_PORT: '8069'
      LIMIT_MEMORY_HARD: '2684354560'
      LIMIT_MEMORY_SOFT: '2147483648'
      LIMIT_TIME_CPU: '600'
      LIMIT_TIME_REAL: '1200'
      LIMIT_TIME_REAL_CRON: '300'
      LIST_DB: "True"
      LOG_DB: "False"
      LOG_DB_LEVEL: warning
      LOG_HANDLER: :INFO
      LOG_LEVEL: debug
      MAX_CRON_THREADS: '2'
      NODE_VERSION: ''
      ODOO_BASEPATH: /opt/odoo
      ODOO_DATA_DIR: /var/lib/odoo/data
      ODOO_EXTRA_ADDONS: /mnt/extra-addons
      ODOO_LOGS_DIR: /var/lib/odoo/logs
      ODOO_RC: /etc/odoo/odoo.conf
      ODOO_VERSION: '13.0'
      POSTGRES_PASSWORD: odoo
      POSTGRES_USER: odoo
      PROXY_MODE: "False"
      PSQL_VERSION: '11'
      SERVER_WIDE_MODULES: base,web
      SMTP_PASSWORD: "False"
      SMTP_PORT: '25'
      SMTP_SERVER: localhost
      SMTP_SSL: "False"
      SMTP_USER: "False"
      TEST_ENABLE: "False"
      UNACCENT: "False"
      WDB_NO_BROWSER_AUTO_OPEN: "True"
      WDB_SOCKET_SERVER: wdb
      WDB_WEB_PORT: '1984'
      WITHOUT_DEMO: "False"
      WKHTMLTOPDF_CHECKSUM: ''
      WKHTMLTOX_VERSION: ''
      WORKERS: '3'
    image: iterativodo/dockerdoo:13.0
    networks:
      odoonet: {}
    ports:
    - published: 8069
      target: 8069
    - published: 8072
      target: 8072
    restart: unless-stopped
    volumes:
    - /Users/username/src/go/src/github.com/x0rzkov/dockerdoo/src/odoo://opt/odoo:rw
    - /Users/username/src/go/src/github.com/x0rzkov/dockerdoo/.devcontainer/.vscode:/etc/.vscode:rw
    - /Users/username/src/go/src/github.com/x0rzkov/dockerdoo/config:/etc/odoo:rw
    - /Users/username/src/go/src/github.com/x0rzkov/dockerdoo/custom:/mnt/extra-addons:rw
    - odoo-data:/var/lib/odoo/data:rw
    - odoo-testlogs:/var/lib/odoo/logs:rw
  wdb:
    depends_on:
    - db
    image: kozea/wdb:3.3.0
    networks:
      odoonet: {}
    ports:
    - published: 1984
      target: 1984
    restart: unless-stopped
version: '3.7'
volumes:
  odoo-data: {}
  odoo-testlogs: {}
  psql: {}
```

**Comment by gustavovalverde** [comment]
Hi @x0rzkov sorry for the late answer. Your first volume on the config seems odd with '//'

I'll be testing this scenario. 

By the way, thanks for the reference to docker-sync, seems like a good addition.

**Comment by gustavovalverde** [comment]
cc: @akevinieron

**Comment by x0rzkov** [comment]
I removed the trailing slash but no more luck on this one:

Here is the compose output:
```bash
odoo_1  | The variable $ODOO_EXTRA_ADDONS is empty, using default addons_path
odoo_1  | /entrypoint.sh: line 86: /opt/odoo/odoo-bin: No such file or directory
odoo_1  | The variable $ODOO_EXTRA_ADDONS is empty, using default addons_path
odoo_1  | /entrypoint.sh: line 86: /opt/odoo/odoo-bin: No such file or directory
dockerdoo_odoo_1 exited with code 127
odoo_1  | The variable $ODOO_EXTRA_ADDONS is empty, using default addons_path
odoo_1  | /entrypoint.sh: line 86: /opt/odoo/odoo-bin: No such file or directory
dockerdoo_odoo_1 exited with code 127
odoo_1  | The variable $ODOO_EXTRA_ADDONS is empty, using default addons_path
odoo_1  | /entrypoint.sh: line 86: /opt/odoo/odoo-bin: No such file or directory
```

**Comment by gustavovalverde** [comment]
I tested you scenario with the instructions on the readme:
![image](https://user-images.githubusercontent.com/16890942/70862128-86cff400-1f0e-11ea-97b8-d07e612065b8.png)

![image](https://user-images.githubusercontent.com/16890942/70862138-b4b53880-1f0e-11ea-9878-38ba3c8ab36a.png)

![image](https://user-images.githubusercontent.com/16890942/70862143-d8787e80-1f0e-11ea-8546-3d97f85fae7e.png)

It worked without issues. Is the Odoo source in `src/odoo` on your host?

**Comment by gustavovalverde** [comment]
I even see some odd logs from your postgres server.
```shell
db_1    | 2019-12-12 14:49:05.509 UTC [25] LOG:  invalid record length at 0/1652F38: wanted 24, got 0
```

**Comment by x0rzkov** [comment]
are you on linux or macosx ?

**Comment by gustavovalverde** [comment]
Linux

**Comment by x0rzkov** [comment]
that s why we use docker-sync as it is not properly managed by docker for the moment


example of docker-sync.yml
```yaml
version: "2"

options:
  verbose: true
  compose-file-path: 'docker-compose.yml'

syncs:
  #IMPORTANT: ensure this name is unique and does not match your other container names
  #REFERENCE: https://github.com/EugenMayer/docker-sync/blob/master/example/docker-sync.yml#L32 
  odoo-src:
    notify_terminal: false
    src: ${PWD}/src # host source directory
    sync_strategy: 'native_osx' # for osx use 'native_osx', for windows use 'unison'
    # watch_strategy: 'fswatch'
    # sync_userid: 1000 # giving permissions to www-data user (as defined in nginx and php-fpm Dockerfiles)
    sync_args:
    - "-prefer newer"
    - "-ignore='Path .git'"
    - "-ignore='BelowPath .git'"
    sync_excludes: [ '.DS_Store', '.git', '.idea', 'node_modules' ]
    # sync_excludes: ['signored_folder_example'] # ignored directories    
    # this is only available if you use docker-for-mac edge for now
    # host_disk_mount_mode: 'cached' # see https://github.com/moby/moby/pull/31047
    # other unison options can also be specified here, which will be used when run under osx,
    # and ignored when run under linux
```
